name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install bcryptjs@2.4.3
        npm install express@4.18.2
        npm install express-validator@7.0.1
        npm install jsonwebtoken@9.0.0
        npm install mongoose@7.3.1
        npm install swagger-jsdoc@6.2.8
        npm install swagger-ui-express@4.6.3
        npm install jest@29.5.0
    - run: npm test